Ypsw 191
yumapos/Yumapos-WCF-Generator pull request #54
Opened 2017-05-29 14:55 UTC by marypop

https://github.com/yumapos/YumaPos-Server-WCF/pull/1687

2017-05-29 17:02 UTC, AntonSmirnovYumasoft reviewed
Общие пожелания
- тестовая генерация для одной и другой бд
- рефакторинг в сторону "списка доступных БД",  заменить IsPostgres на 
```C#
enum DBType
{
MSSql,
Postgres,
....
}

2017-05-29 17:02 UTC, AntonSmirnovYumasoft commented on Sandbox/TestRepositoryGeneration/GeneratedRepositories/AddressRepository.g.cs
>  	{
Тестовый проект должен содержать примеры генерации и для MS SQL и для Postgres.

2017-05-29 17:02 UTC, AntonSmirnovYumasoft commented on WCF-Generator.exe.config
> +            IsPostgresDb="true"/>
тут что-то вроде перечисления нужно "DBType = Postgres", не совсем очевидно что указать false то будет для MS SQL генерить

2017-05-29 17:02 UTC, AntonSmirnovYumasoft commented on WCF-Generator/RepositoriesGeneration/Configuration/Settings.cs
> +        [ConfigurationProperty("IsPostgresDb", DefaultValue = false, IsRequired = false)]
"DBType = Postgres"

2017-05-29 17:02 UTC, AntonSmirnovYumasoft commented on WCF-Generator/RepositoriesGeneration/Core/CodeClassGeneratorRepository.cs
> +            if (sqlInfo.IsPostgresDb)
Неплохо бы сразу зарефачить этот момент и избавиться от многочисленных ```if```

Cделать CodeClassGeneratorRepository базовым классом (+ переименовать по-человечески. Да, да, я назвал коряво, но исправить надо)

```C#
class MSSqlRepositoryCodeClassGenerator  :  RepositoryCodeClassGeneratorBase {
бла-бла генерю для MS sql
}
class PostgresRepositoryCodeClassGenerator  : RepositoryCodeClassGeneratorBase {
бла-бла-бла генерю для postgres
}
```
в котором уже будут различия между БД видны

2017-05-29 17:02 UTC, AntonSmirnovYumasoft commented on WCF-Generator/RepositoriesGeneration/Core/CodeClassGeneratorVersionsRepository.cs
> +                if (RepositoryInfo.IsPostgresDb)
Тоже самое, рефачить, убирать ```if```,  разбивать на два класса, переименовать в   VersionsRepositoryCodeClassGenerator

2017-05-29 17:02 UTC, AntonSmirnovYumasoft commented on WCF-Generator/RepositoriesGeneration/Infrastructure/RepositoryInfo.cs
> +        public string PostgresTableName { get; set; }
Использовать  "TableName" a тип базы анализировать по DBType (Придется добавить пропертю DBType и enum)

2017-05-29 17:02 UTC, AntonSmirnovYumasoft commented on WCF-Generator/RepositoriesGeneration/Infrastructure/RepositoryInfo.cs
> +        public bool IsPostgresDb { get; set; }
все-таки enum DBType

2017-05-30 08:32 UTC, AntonSmirnovYumasoft commented
Доки по генерации обновить тут https://github.com/yumapos/Yumapos-WCF-Generator/wiki/%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B5%D0%B2

2017-05-30 15:22 UTC, knaiv requested changes
Согласен с замечаниями Антона

2017-06-06 16:33 UTC, dj-raphael approved these changes

2017-06-06 16:35 UTC, merged

2017-06-07 07:07 UTC, AntonSmirnovYumasoft reviewed
Генерацию декоратора вернуть. За исправленные опечатки спасибо.

2017-06-07 07:07 UTC, AntonSmirnovYumasoft commented on Sandbox/TestDecoratorGeneration/Service.cs
> +        [IgnoreDecoration]
А что заигнорили все методы в тестовом проекте для декоратора?