Decorator, generate methods for dateTime filters
yumapos/Yumapos-WCF-Generator pull request #55
Opened 2017-06-08 15:36 UTC by marypop

https://github.com/yumapos/YumaPos-Server-WCF/pull/1711
https://github.com/yumapos/YumaPos-Server-Core/pull/214

2017-06-08 17:11 UTC, dj-raphael commented on Sandbox/TestRepositoryGeneration/GeneratedRepositories/AddressRepository.g.cs
> +		private const string WhereQueryByBetweenModified = "WHERE  [dbo].[Addresses].[Modified] >= @startModified AND [dbo].[Addresses].[Modified] < @endModified";
не надо создавать новый тип запросов, надо модифицировать старый!

2017-06-08 18:39 UTC, dj-raphael approved these changes

2017-06-09 07:49 UTC, AntonSmirnovYumasoft requested changes

2017-06-09 07:49 UTC, AntonSmirnovYumasoft commented on WCF-Generator/Program.cs
> +            //try
Раскоментируй, а то будем думать почему не генериться

2017-06-09 11:16 UTC, AntonSmirnovYumasoft approved these changes

2017-06-09 11:31 UTC, dj-raphael approved these changes

2017-06-09 11:32 UTC, merged